lane :scanning do

  scan(
    code_coverage: true,
    scheme: "FWJoystickExemple",
    device: "iPhone 5s (9.0)"
  )
  xcov(
    scheme: "FWJoystickExemple",
    device: "iPhone 5s (9.0)"
  )

end

lane :deploy do

  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "ridergoster/joystick-swift-framework",
      name: version,
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
    pod_push()
  end

end
