lane :scan do

  scan(
    code_coverage: true
  )
  xcov

end

lane :deploy do

  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "ridergoster/joystick-swift-framework",
      name: version,
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
    pod_push()
  end

end
